// Code generated by "stringer -type ExKind ."; DO NOT EDIT.

package excfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExKindInvalid-0]
	_ = x[ExKindStmt-1]
	_ = x[ExKindIf-2]
	_ = x[ExKindSubExpr-3]
	_ = x[ExKindBool-4]
}

const _ExKind_name = "ExKindInvalidExKindStmtExKindIfExKindSubExprExKindBool"

var _ExKind_index = [...]uint8{0, 13, 23, 31, 44, 54}

func (i ExKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExKind_index)-1 {
		return "ExKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExKind_name[_ExKind_index[idx]:_ExKind_index[idx+1]]
}
